### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'E:\strapi-starter-gatsby-blog-v2\frontend\.cache\json\_.json'

### ISSUE THREAD

**Issue by abhiilash** [strapi/strapi-starter-gatsby-blog#12]
Error: ENOENT: no such file or directory, open 'E:\strapi-starter-gatsby-blog-v2\frontend\.cache\json\_.json'

**Comment by remidej** [comment]
I need more details to help you. What command did you run?

**Comment by markkaylor** [comment]
Hello @abhiilash !

As we have not received any new or updated information in over 14 days we are marking this issue/discussion as closed. Should you have new information please feel free to respond and we can consider reopening it.

For others finding this closed issue and you have updated information, please open up a new bug report and simply reference this closed bug report so that we can get any new information you may have. If you have questions please refer to the contributor's guide on opening issues.

Thank you and have a great day!
