### ISSUE TITLE
Leverage SEO component for Articles

### ISSUE THREAD

**Issue by soft4net** [strapi/strapi-starter-gatsby-blog#13]
We have SEO component, which is right now used only for "SINGLE TYPES" Global and Homepage.
Moreover Articles collection uses own field "description" for SEO purposes, why not reuse SEO component for Articles as well?

**Comment by remidej** [comment]
Hello and thanks for raising this interesting issue, we're always happy to hear some feedback.

I like to think of the SEO component as a place for metadata, fields that are only used for crawlers. Here, the title, description and image fields aren't for SEO purposes, they're the heart of the article. I think for the content editing experience, it didn't feel right to delegate these to the metadata corner.

On the other hand, Global and Homepage need the SEO component because it contains data that's really "meta": though it's related, you can't infer it from the main content.

I also like this approach because it allows us to shows two ways to handle SEO in the same starter, but it can indeed be confusing.
